# .github/dependabot.yml - Version optimisée pour la production
version: 2
updates:
  # Dependencies frontend critiques
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Brussels"
    open-pull-requests-limit: 8
    target-branch: "develop"
    reviewers:
      - "votre-username"
    assignees:
      - "votre-username"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    # Ignorer les mises à jour majeures pour éviter les breaking changes
    ignore:
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@types/*"
        update-types: ["version-update:semver-major"]
    # Autoriser uniquement les deps critiques de sécurité
    allow:
      - dependency-type: "security"
      - dependency-name: "ethers"
      - dependency-name: "viem"
      - dependency-name: "@reown/*"

  # Docker - Images de base critiques
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: "node"
        update-types: ["version-update:semver-major"]

  # GitHub Actions - Sécurité workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    allow:
      - dependency-type: "security"
